"CreateSamples/x64/Debug/CreateSamples.exe"^
 "BadExampleVideos/lp.avi"^
 "BadExamples"^
 200^
 40^
 60^
 60
 "CreateSamples/x64/Debug/CreateSamples.exe"^
 "BadExampleVideos/impala.avi"^
 "BadExamples"^
 200^
 40^
 60^
 60
  "CreateSamples/x64/Debug/CreateSamples.exe"^
 "BadExampleVideos/boc.avi"^
 "BadExamples"^
 200^
 40^
 60^
 60
   "CreateSamples/x64/Debug/CreateSamples.exe"^
 "BadExampleVideos/cloudatlas.avi"^
 "BadExamples"^
 500^
 100^
 60^
 60
pause